name: Latest blog post workflow
on:
  workflow_dispatch:
  push:
    branches:
      - master
  schedule:
    # Runs every hour
    - cron: '0 * * * *

jobs:
  update-readme:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          max_post_count: 4
          feed_list: "https://dev.to/feed/gautamkrishnar,https://www.gautamkrishnar.com/feed/"
